# Generated by Django 4.0.6 on 2022-11-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_name',
            new_name='dept',
        ),
    ]
